### ISSUE TITLE
New things

### ISSUE THREAD

**Issue by wikiselev** [hemberg-lab/scRNA.seq.course#119]
1. Imputation chapter
2. Separate chapter for SEURAT
3. Add more better batch correction methods
(optional) 4. Cross-dataset comparison (scmap, metaneighbour, mnnCorrect, CCA-part of Seurat)

**Comment by mhemberg** [comment]
1. Magic and scImpute (and maybe more) (Martin)
2. Adapt one of their tutorials. Do clustering for small and large datasets. (Vlad)
3. Discuss batch correction methods (Tallulah)
4. Cross-dataset comparisons (Vlad)
5. Introduction to BioConductor classes (Davies)

**Comment by mhemberg** [comment]
3. Internal batch correction (as before) AND Compare across datasets
4. Mapping/projection

**Comment by tallulandrews** [comment]
Shall we remove the edgeR DE stuff from the counfounders chapter? It isn't very useful & somewhat off-topic.

**Comment by wikiselev** [comment]
Yes, I agree, please feel free to do it. I have updated everything until clustering chapters. Hopefully will be able to build the new version tomorrow, will let you know.

**Comment by wikiselev** [comment]
I have removed DE stuff from confounders chapter

**Comment by tallulandrews** [comment]
To myself - may need to sort assayNames to make figures more interpret-able. & check how bit a mess it is with the millions of figures....
