### ISSUE TITLE
Fig 5: which script was used?

### ISSUE THREAD

**Issue by iiiir** [hemberg-lab/scRNA.seq.course#120]
Hi,
I wonder if you already have script available for the following figure?

`Figure 5.2: Example of the total number of reads mapped to each cell.
`
Thanks a lot,
Shuoguo

**Comment by wikiselev** [comment]
Hi,

I don't think I have a script at hand, but Tallulah @tallulandrews can provide you the details of how she plotted it.

Cheers,
Vlad

**Comment by tallulandrews** [comment]
That figure was made from STAR mapping log files using the table produced by the script below:

https://github.com/tallulandrews/scRNASeqPipeline/blob/master/3_Compile_Mapping_Statistics.pl

However, the necessary information can be obtained from BAM files instead by using the correct FLAGs.

After that it is a simple R barplot:
`
# full is a table with columns: 
# sample = cell ID
# unique = N reads uniquely map 
# multi = N reads multimap (FLAG = 256)
# nomap = N reads unmapped (FLAG = 4)
Iexcl=which(full$sample %in% exclude) # for red arrows
Iques=which(full$sample %in% questionable) # for yellow arrows

par(cex=2)
png("Figure.png", width=2*4, height=4, units="in", res=300)
par(mar=c(4,4,1,1))
mycolours = c("grey35", "grey65","grey95")
toplot = rbind(full$unique, full$multi,full$nomap)/1000000
xes = barplot(toplot, xlab="Cells", ylab="Millions of Reads", las=1, col=mycolours)
yes = colSums(toplot)
legend("topleft", fill=mycolours, c("Uniquely Map", "Multi Map", "Unmapped"))

arrows(xes[Iexcl],yes[Iexcl]+1,xes[Iexcl],yes[Iexcl]+0.1, col="red", lwd=2, len=0.1)
arrows(xes[Iques],yes[Iques]+1,xes[Iques],yes[Iques]+0.1, col="goldenrod", lwd=2, len=0.1)
dev.off();
`

**Comment by iiiir** [comment]
Thank you very much. I do not have the STAR log saved so will write something to plot the histogram.

-Shuoguo

**Comment by olechnwin** [comment]
Hi,
I'm still confused on how to create the figure. The output from STAR is number of reads for the entire bam file, it doesn't provide the number of reads per cell. So, how did you get the number of reads (mapped, unique, multi-mapped) per cell?
Is there a way to get these numbers from bam files?
Thanks!

**Comment by tallulandrews** [comment]
How did you store the cell-barcode associated with each read?
If it is part of the read name then you will have to use a script/additional command to select reads by cell-barcode. 
Alternatively you can split your .fastq files by the cell-barcode before mapping them.
But if you have data from a droplet-based technology you need to identify barcodes that correspond to droplets with cells-in them using either the inversion point in the #UMI plot (like cell-ranger) or using "EmptyDrops" : https://github.com/TimothyTickle/hca-jamboree-cell-identification/tree/master/src/poisson_model/package
or "dropEst"  : https://github.com/hms-dbmi/dropEst
