### ISSUE TITLE
Unable to download PDF version of course material

### ISSUE THREAD

**Issue by leonfodoulian** [hemberg-lab/scRNA.seq.course#144]
Hi,

I am unable to download the PDF version of the course material found on the [this website page](http://hemberg-lab.github.io/scRNA.seq.course/). The page error I'm getting [is the following](http://hemberg-lab.github.io/scRNA.seq.course/scRNA-seq-course.pdf).

Any way this issue can be fixed?

Best,
Leon

**Comment by wikiselev** [comment]
Hi Leon, now you should be able to download the pdf, please try again and sorry for inconvenience!
