### ISSUE TITLE
obscure normalization results

### ISSUE THREAD

**Issue by MichaelPeibo** [hemberg-lab/scRNA.seq.course#145]
Hi,
I am using some normalization method to normalize my data set, which is originally from 10X genomics, I managed it using SingleCellExperiment class using scater package;
after filtering with MT, total counts, total features, I did normalization as told in course, however, when I plot RLE, I got these strange results, which seems to be more 'normalized' in Raw than normalized with methods, shown below:
[scranNorm.pdf](https://github.com/hemberg-lab/scRNA.seq.course/files/1773299/scranNorm.pdf)

[TMMnorm.pdf](https://github.com/hemberg-lab/scRNA.seq.course/files/1771804/TMMnorm.pdf)
[UQnorm.pdf](https://github.com/hemberg-lab/scRNA.seq.course/files/1771805/UQnorm.pdf)
[RLEnorm.pdf](https://github.com/hemberg-lab/scRNA.seq.course/files/1771806/RLEnorm.pdf)
[CPMnorm.pdf](https://github.com/hemberg-lab/scRNA.seq.course/files/1771807/CPMnorm.pdf)

for me, TMM seems to be good, but not others, especially for scran;
any explanation for this?
Thanks!

**Comment by wikiselev** [comment]
Sorry, I think, we don't have resources to look at each individual case, hope you've solve this problem.
