### ISSUE TITLE
STAR_explanation.png is missing

### ISSUE THREAD

**Issue by yeroslaviz** [hemberg-lab/scRNA.seq.course#167]
thanks for this great course.
In 3.5 the image for the STAR aligner is missing.
please either remove the link to it, or add the image again

thanks

**Comment by nyaapass** [comment]
Same problem here, some figure links in chapter [3.5 Using STAR to Align Reads](https://github.com/hemberg-lab/scRNA.seq.course/blob/master/course_files/process-raw-align.Rmd) are broken:

- [`L1-images/STAR_explanation.png`](https://github.com/hemberg-lab/scRNA.seq.course/blob/b150dddc4535b170b4e40940b4dfaf349d477db2/course_files/process-raw-align.Rmd#L16)
- [`L1-images/Kmers.png`](https://github.com/hemberg-lab/scRNA.seq.course/blob/b150dddc4535b170b4e40940b4dfaf349d477db2/course_files/process-raw-align.Rmd#L59)
- [`L1-images/TCC.jpg`](https://github.com/hemberg-lab/scRNA.seq.course/blob/b150dddc4535b170b4e40940b4dfaf349d477db2/course_files/process-raw-align.Rmd#L78)

And thanks so much for this course too, it helps me a lot.

**Comment by nyaapass** [comment]
PR was created to fix this problem (#174).

**Comment by wikiselev** [comment]
Many thanks for our help! Sorry, we've been a bit quiet recently, but hopefully the major update of the course is coming next year!
