### ISSUE TITLE
function isSpike is deprecated

### ISSUE THREAD

**Issue by dianaliduke** [hemberg-lab/scRNA.seq.course#171]
Hi all, your code including isSpike is not working correctly, because isSpike is now a deprecated function. Please advise on how to proceed. 

<img width="725" alt="Screen Shot 2020-05-15 at 11 44 20 AM" src="https://user-images.githubusercontent.com/62430809/82069532-7086b980-96a1-11ea-8627-1a65080d3fe3.png">

**Comment by yachenshen2017** [comment]
Hi,
    Did you find the way to instead of isSpike in R? I have the same problem.
    Thanks

**Comment by dianaliduke** [comment]
Hi,
I did not. I am trying to learn how to analyze data from drop-seq single cell RNA sequencing, and I realized that I do not need the isSpike function or the newer AltExp function to analyze data from drop-seq. 

Someone answered my same question on bioinformatics stack exchange though. please follow the link here. 

https://bioinformatics.stackexchange.com/questions/13295/isspike-function-in-singlecellexperiment-package-is-deprecated
