### ISSUE TITLE
Can not run the docker image

### ISSUE THREAD

**Issue by alexxue81** [hemberg-lab/scRNA.seq.course#175]
Hi,

I tried to run

`docker run -p 8888:8888 -e PASSWORD="jupyter" quay.io/hemberg-group/scrna-seq-course:v4.11
`
But it was stuck at the last file
"
5bcb3f516c99: Pull complete
3026db1e6d3a: Pull complete
c4b2b52a500c: Pull complete
8cde90254c69: Pull complete
350e3cbd34fa: Pull complete
3da29f383baa: Pull complete
75885a9c477d: Pull complete
88c017945f07: Pull complete
3faa38653212: Waiting
"

Is there any way to solve this? Thank you!

Cheers,
Angli

**Comment by prete** [comment]
Hi @alexxue81 please try first pulling the image and run it.

1. Pull the image. Bear in mind that the image size is ~7.5GB so it may take a while depending on your internet speed.
```bash
docker pull quay.io/hemberg-group/scrna-seq-course:v4.11
```

2. Run the pulled image
```bahs
docker run -p 8888:8888 -e PASSWORD="jupyter" quay.io/hemberg-group/scrna-seq-course:v4.11

```

**Comment by alexxue81** [comment]
Hi Prete,

Thanks for your reply.

I first pull the image but it is still waiting in the "3faa38653212". For other files, it will show the process bar. 

Is the link for this file broken?

Cheers,
Angli

**Comment by prete** [comment]
Are you by any chance trying this on a Mac? Seems like it's a bug in docker for mac that happens sometimes: https://github.com/docker/for-mac/issues/2083

Restarting docker service should fixed the issue. 

Additionally you can delete the partially download layers using `docker image rm -f quay.io/hemberg-group/scrna-seq-course:v4.11` before trying to pull again.

**Comment by alexxue81** [comment]
It works. Thank you!
