### ISSUE TITLE
File molecules.txt missing

### ISSUE THREAD

**Issue by SteliosKI** [hemberg-lab/scRNA.seq.course#178]
Hej hej! I cannot find the file molecules.txt that is required for the analysis. Could you upload it? Thank you

**Comment by apredeus** [comment]
Hello @SteliosKI, 

This file is a part of data folder, which I think is a bit big to be on GitHub. You can either use the Docker, or download the files [here](https://scrnaseq-course.cog.sanger.ac.uk/index.html?prefix=data/).

**Comment by SteliosKI** [comment]
I just go to the workshop homepage..

**Comment by SteliosKI** [comment]
Tack! :)

**Comment by apredeus** [comment]
Sorry, this is the correct link: https://singlecellcourse.cog.sanger.ac.uk/index.html?prefix=data/

**Comment by mugpeng** [comment]
> Sorry, this is the correct link: https://singlecellcourse.cog.sanger.ac.uk/index.html?prefix=data/

![image](https://user-images.githubusercontent.com/52995448/143735388-3eab97cb-3102-4af6-b2ad-dd608acaf61b.png)

I can't visit the website now, is that anything wrong?

**Comment by prete** [comment]
Hi. I just tried it and seems to be working now. Perhaps it was a transient error.

Alternative links for the data are:
- https://www.singlecellcourse.org/data/
- https://singlecellcourse.cog.sanger.ac.uk/index.html?prefix=data/

Let us now if you're still seeing this error.

**Comment by HeatherKates** [comment]
Along the same lines, I can't find the counts.txt file at the data links.
`tung_counts <- read.table("data/tung/counts.txt", sep = "\t")`
Thank you
