### ISSUE TITLE
code missing in the biological-analysis#clust-methods

### ISSUE THREAD

**Issue by huang-sh** [hemberg-lab/scRNA.seq.course#182]
Hi, I think some code is missing here (https://www.singlecellcourse.org/biological-analysis.html#clust-methods)
such as:
![image](https://user-images.githubusercontent.com/24741118/147848216-fd2de5c1-ce7d-4429-a03c-a4a6e0cc70de.png)
![image](https://user-images.githubusercontent.com/24741118/147848265-bfb88252-4f1d-49ed-bc57-d59933ef190b.png)

**Comment by prete** [comment]
Indeed seems to be missing. You can look at the raw notebook for that section here: [course_files/07a-Clustering.Rmd](https://github.com/hemberg-lab/scRNA.seq.course/blob/master/course_files/07a-Clustering.Rmd) or directly at the chunks:
- [7.2.1 Deng dataset](https://github.com/hemberg-lab/scRNA.seq.course/blob/master/course_files/07a-Clustering.Rmd#L114)
- [7.2.2 SC3](https://github.com/hemberg-lab/scRNA.seq.course/blob/master/course_files/07a-Clustering.Rmd#L137)

**Comment by huang-sh** [comment]
thank you , I see

**Comment by huang-sh** [comment]
thank you , I see

**Comment by prete** [comment]
Should be fixed in the next release.
