### ISSUE TITLE
There is no data/tung folder 

### ISSUE THREAD

**Issue by Nayrouz109** [hemberg-lab/scRNA.seq.course#186]
Hello, 

I am following the manual installation of the course by cloning the Github repo. However, I see in the instructions that the data files are located in the data/tung folder. However, I there is no /data folder. 

Thanks,

**Comment by prete** [comment]
Hi @Nayrouz109  to download the data you need to execture the `poststart.sh` script and then move the new `data` folder to it's correct location. 
For example, open a Terminal and follow these steps:
1. **Clone the repository**
```bash
git clone https://github.com/hemberg-lab/scRNA.seq.course.git 
```
2. **Download the data**
```bash
cd scRNA.seq.course
./poststart.sh
```
3. **Move the downloaded data folder to the `course_files` folder**
```bash
mv data course_files/ 
```

Now you should be able to run the file courses from within the `course_files` folder.

**Comment by Nayrouz109** [comment]
I keep getting `./poststart.sh: line 4: aws: command not found` . So I will need to install AWS CLI ?

**Comment by prete** [comment]
Yes, as descibred in the docs, if you want to download data files outside of Docker image you will need to install [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html) on your computer.

Alternatively, you can browse and download the files individually in you web-browser by visiting [this link](https://singlecellcourse.cog.sanger.ac.uk/index.html?shared=data/).

**Comment by Nayrouz109** [comment]
Sweet. Thanks much for the clarification !!
